export const projects = [{
  id: '1',
  name: 'People like me',
  url: 'http://www.people-like-me.co/',
  description: "Wise ways for finding accommodation for a cancer relative.",
  img_src: "www.imgur.com/1",
}, {
  id: '2',
  name: 'Air plane transporter',
  description: "A mobile game where you can construct your own fleet of ariplanes",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '3',
  name: 'Carmel',
  description: "Grow Your Tech Skills With Programming Challenges And Earn Experience Points",
  url: 'https://carmel.io/team',
  img_src: "www.imgur.com/1",
}, {
  id: '4',
  name: 'Project 4',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '5',
  name: 'Project 5',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '6',
  name: 'Project 6',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '7',
  name: 'Project 7',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '8',
  name: 'Project 8',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '9',
  name: 'Project 9',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
},];