export const projects = [{
  id: '1',
  name: 'Landscape Architecture Portfolio',
  url: 'https://agentchris.github.io/landscape-arhitect-portofolio/#/',
  description: "Landscape Architecture Portfolio using three.js,webgl and lots of animations.",
  img_src: "https://trello-attachments.s3.amazonaws.com/5d5a6623b561498e086312d5/5d796927419efc67ceeb07c3/0983c966b530a22a7622fabbc8f2cf09/landscape_project.png",
}, {
  id: '2',
  name: 'Air plane transporter',
  description: "A mobile game where you can construct your own fleet of ariplanes",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '3',
  name: 'Carmel',
  description: "Grow Your Tech Skills With Programming Challenges And Earn Experience Points",
  url: 'https://carmel.io/team',
  img_src: "www.imgur.com/1",
}, {
  id: '4',
  name: 'Project 4',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '5',
  name: 'Project 5',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '6',
  name: 'Project 6',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '7',
  name: 'Project 7',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '8',
  name: 'Project 8',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
}, {
  id: '9',
  name: 'Project 9',
  description: "A short description",
  url: 'http://www.people-like-me.co/',
  img_src: "www.imgur.com/1",
},];